name: Test

triggers:
  - uses: cron
    expr: "0 * * * *"

actions:
  - name: List files
    uses: command
    args: ls -la
  - name: Clone matplotlib-scalebar
    uses: git-checkout
    repos_url: https://github.com/ppinard/matplotlib-scalebar.git
    branch: master
  - name: Run tests
    uses: pytest
    relpath: matplotlib-scalebar

notifications:
  - uses: email
    recipients:
      - az8587259@gmail.com
