name: Test

triggers:
  - uses: cron
    expr: "* * * * *"

actions:
  - name: List files
    uses: command
    args: ls -la
  - name: Clone matplotlib-scalebar
    uses: git-checkout
    repos_url: https://github.com/ppinard/matplotlib-scalebar.git
    branch: master
