# Generated by Django 3.2.9 on 2021-12-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(null=True)),
                ('state', models.CharField(choices=[('not started', 'Not Started'), ('running', 'Running'), ('error', 'Error'), ('failed', 'Failed'), ('success', 'Success')], default='not started', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ActionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('started_on', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(null=True)),
                ('state', models.CharField(choices=[('not started', 'Not Started'), ('running', 'Running'), ('error', 'Error'), ('failed', 'Failed'), ('success', 'Success')], default='not started', max_length=12)),
                ('output', models.TextField(null=True)),
                ('jobrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionruns', to='django_cd.jobrun')),
            ],
        ),
    ]
