# Generated by Django 3.2.9 on 2021-12-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_cd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionrun',
            name='state',
            field=models.CharField(choices=[('not started', 'Not Started'), ('running', 'Running'), ('error', 'Error'), ('failed', 'Failed'), ('success', 'Success'), ('skipped', 'Skipped')], default='not started', max_length=12),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='state',
            field=models.CharField(choices=[('not started', 'Not Started'), ('running', 'Running'), ('error', 'Error'), ('failed', 'Failed'), ('success', 'Success'), ('skipped', 'Skipped')], default='not started', max_length=12),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('not started', 'Not Started'), ('running', 'Running'), ('error', 'Error'), ('failed', 'Failed'), ('success', 'Success'), ('skipped', 'Skipped')], default='not started', max_length=12)),
                ('duration', models.DurationField()),
                ('actionrun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testresults', to='django_cd.actionrun')),
            ],
        ),
    ]
