# Generated by Django 3.2.9 on 2021-12-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cd', '0002_auto_20211219_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='output',
            field=models.TextField(null=True),
        ),
    ]
